version: '3'
services:
  mongo:
    image: mongo
    environment:
      - AUTH=no
    ports:
      - 27017:27017

  api:
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 4567:4567
    command: rackup config.ru -o 0.0.0.0
    links:
      - mongo

  lib:
    build: ./lib
    volumes:
      - ./lib:/lib
