# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 2.0"
gem "mongo", "~> 2.5"

group :test do
  gem "rspec", "~> 3.7"
  gem "rack-test", "~> 0.8.2"
end
